# Generated by Django 4.1.5 on 2023-05-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre de Ruta')),
                ('addres', models.CharField(max_length=230, verbose_name='Direccion')),
                ('latitude', models.FloatField(verbose_name='Latitud')),
                ('length', models.FloatField(verbose_name='Longitud')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['name'],
            },
        ),
    ]
